#! /usr/bin/env bash
# ___________________________________________________________________________ #
#                                                                             #
#       JarExtract -- Recursively extract Java archives.                      #
#                                                                             #
#                                                                             #
#    Licensed under the Apache License, Version 2.0 (the "License");          #
#    you may not use this file except in compliance with the License.         #
#    You may obtain a copy of the License at                                  #
#                                                                             #
#        http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#    distributed under the License is distributed on an "AS IS" BASIS,        #
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
#    See the License for the specific language governing permissions and      #
#    limitations under the License.                                           #
# ___________________________________________________________________________ #
#                                                                             #
#                                                                             #
# Copyright 2007, lhunath                                                     #
#   * http://lhunath.lyndir.com                                               #
#   * Maarten Billemont.                                                      #
#                                                                             #
source "${0%/*}/bashlib"                                                      #

emit "Extracting archives recursively" --
    mkdir -p "$workdir/"{old,new}

    cd "$workdir/old" && unzip -qq "$old" || \
        { emit -$?; exit $?; }
    cd "$workdir/new" && unzip -qq "$new" || \
        { emit -$?; exit $?; }

    keepDigging=1
    for (( i=0; keepDigging; ++i )); do
        emit "Starting level $i"
        for d in old new; do
            cd "$workdir/$d"
            if (( i )); then
                keepDigging=0
                while read -d ''; do
                    cd "$REPLY"

                    extractAll || \
                        { emit -$?; exit $?; }

                    keepDigging=1
                done < <(find "$PWD" -mindepth $i -maxdepth $i -type d -name '_*.?ar' -print0)
            else
                extractAll
            fi
        done
    done
emit -0

